name: "Checkout"
description: "Use optimized checkout for custom runners"
inputs:
  runner_provider:
    description: "Runner provider: namespace or github"
    default: "github"
  fetch_depth:
    description: "Fetch depth for actions/checkout"
    default: "1"
  repository:
    description: "Repository name with owner"
    default: "${{ github.repository }}"
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Checkout (Namespace)
      if: ${{ inputs.runner_provider == 'namespace' }}
      uses: namespacelabs/nscloud-checkout-action@v8
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
      env:
        GIT_CONFIG_COUNT: 1
        GIT_CONFIG_KEY_0: checkout.workers
        GIT_CONFIG_VALUE_0: 16

    - name: Checkout (GitHub)
      if: ${{ inputs.runner_provider == 'github' }}
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
      env:
        GIT_CONFIG_COUNT: 1
        GIT_CONFIG_KEY_0: checkout.workers
        GIT_CONFIG_VALUE_0: 4
