name: "Prepare extension"
description: "Checkout extension directories"

inputs:
  duckdb-ref:
    description: "Ref to fetch for duckdb"
    default: "main"
  duckdb-sha:
    description: "Exact commit SHA to checkout for duckdb"
  duckdb-repository:
    description: "Optional custom DuckDB repository to clone"
  ci-tools-ref:
    description: "Ref/branch to checkout for extension-ci-tools"
    default: "main"
  extension-ref:
    description: "Ref/branch to checkout for extension"
    required: true
  extension-repository:
    description: "Extension repository to clone"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.extension-repository }}
        ref: ${{ inputs.extension-ref }}
        fetch-depth: 0
        submodules: recursive

    - name: Checkout custom DuckDB
      if: ${{ inputs.duckdb-repository != '' }}
      uses: actions/checkout@v6
      with:
        path: duckdb
        repository: ${{ inputs.duckdb-repository }}
        ref: ${{ inputs.duckdb-ref }}
        fetch-depth: 0

    - name: Set git ref
      shell: bash
      run: |
        set -eux -o pipefail
        git -C duckdb fetch --prune --tags origin "${{ inputs.duckdb-ref }}"
        git -C extension-ci-tools fetch --prune --tags origin
        if [[ "${{ inputs.duckdb-sha }}" != '' ]]; then
          git -C duckdb checkout "${{ inputs.duckdb-sha }}"
        fi
        git -C extension-ci-tools checkout "${{ inputs.ci-tools-ref }}"

        git config --global --add safe.directory "$PWD"
        git config --global --add safe.directory "$PWD/duckdb"
        git config --global --add safe.directory "$PWD/extension-ci-tools"
